from SCons.Environment import Environment

Import("targetenv") 
targetenv : Environment

buildenv = targetenv.Clone()
buildenv.Append(
    CPPPATH = [ 
        buildenv.Dir('.').srcnode(),
        buildenv['PROJECTDIR'].Dir('src/crt/sdk')
    ],
)

libc_sources = [
    'memory/memcmp.c',
    'memory/memcpy.c',
    'memory/memmove.c',
    'memory/memset.c',
    'string/strlen.c',
    'system/sysinfo.c'
]

libc_objects = buildenv.Object(libc_sources)
libc = buildenv.StaticLibrary('libc.o', libc_objects)

Export('libc')